module.exports = {
    UNAUTHORIZED:'Unathorized Access',
    INTERNAL_SERVER_ERROR:'Internal server error.',
    REQUIRED_DATA:'Please fill all required data.',
    SUCCESSFULLY_DONE:'Data found successfully.',
    SUCCESSFULLY_UPDATE:'Data updated successfully.',
    WENT_WRONG:'Something went wrong',
    SAVED_SUCCESSFULLY:" is saved successfully.",
     ALL_READY_EXIST_EMAIL:'This email is Already exist.',
     NOT_MATCH:"Emailid does not exist.",
     LOGIN_SUCCESS:"Login successfully.",
     NOT_FOUND:"No data found.",
     UPDATE:" is updated successfully.",
     DELETE:" deleted successfully.",
     ALL_READY_EXIST_REGISTRATION_NO:"This registration number is already exists.",
    CORRECT_EMAIL:'Please send correct Email.',
    EMAIL_IS_REQ :'Email is required.',
    NAME_IS_REQ : 'Name is required.',
    ADMIN_PASS_REQ : 'Admin password is required.',
    ADMIN_EMAIL_REQ : 'Admin email is required.',
    CORRECT_ADMIN_EMAIL:'Please send correct admin email.',
    ORG_ADD_SUCCESS : 'Organisation added succesfully.',
    IMG_REQUIRED:'Image is required.',
    IMG_ADD_SUCCESS:'Image uploaded successfully.',
    ADMIN_ID_REQUIRED:'Admin id is required.',
    ORG_ID_REQUIRED:'Organisation id is required.',
    ADMIN_ID_INCORRECT:'Admin id is incorrect.',
    OLD_PASSWORD_INCORRECT:'Old password is incorrect.',
    NEW_CONFIRM_INCORRECT:'New and confirm password are not similar.',
    PASSWORD_UPDATE_SUCCESS:"Your password updated successfully."
 };